MyFirstMVCApplication/Models/DogViewModel.cs
namespace MyFirstMVCApplication.Models
{
    public class DogViewModel
    {
        public string Name { get; set; }

        public string Age { get; set; }

    }
}

MyFirstMVCApplication/Models/ErrorViewModel.cs
namespace MyFirstMVCApplication.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

MyFirstMVCApplication/Controllers/HelloWorldController.cs
using Microsoft.AspNetCore.Mvc;
using MyFirstMVCApplication.Models;

namespace MyFirstMVCApplication.Controllers
{
    public class HelloWorldController : Controller
    {
        private static List<DogViewModel> dogs = new List<DogViewModel>();

        public IActionResult Index()
        {
            return View(dogs);
        }

        public IActionResult Create()
        {
            //Clean view model as we are also creating a new dog in this view
            var dogvM = new DogViewModel();
            return View(dogvM);
        }

        public IActionResult CreateDog(DogViewModel dogViewModel)
        {
            //return View("Index");

            //This is going to redirect to an action in this controller.
            dogs.Add(dogViewModel);
            return RedirectToAction(nameof(Index));
        }

    }
}

MyFirstMVCApplication/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using MyFirstMVCApplication.Models;
using System.Diagnostics;

namespace MyFirstMVCApplication.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        public IActionResult Demo()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

MyFirstMVCApplication/Views/HelloWorld/Create.cshtml
@model DogViewModel

<h1>Add A New Dog</h1>

<hr />

<div class="row">
    <div class="col-6">

        <div class="card">
            <div class="card-header">
                <h5>Add A New Dog</h5>
            </div>
            <div class="card-body">
                <form asp-controller="HelloWorld" asp-action="CreateDog" method="post">
                    <div class="mb-3">
                        <label class="form-label">Dog Name</label>
                        @* asp-for is going to bind this input to the object in the model *@
                        <input asp-for=Name class="form-control" type="text" />
                    </div>
                    <div class="mb-3">
                        <label class="form-label">Dog Age</label>
                        @* asp-for is going to bind this input to the object in the model *@
                        <input asp-for=Age class="form-control" type="number" />
                    </div>
                    <div class="mb-3">
                        <button type="submit" class="btn btn-primary">Save</button>
                    </div>  
                </form>
            </div>
            <div class="card-footer">
            </div>
        </div>

    </div>
</div>

MyFirstMVCApplication/Views/HelloWorld/Index.cshtml
@model List<MyFirstMVCApplication.Models.DogViewModel>

@*
    
*@
@{
}

<h1>Hello World!!</h1>
<p>This is the Index page of the HelloWorld Controller</p>

<ul>
@foreach(var dog in Model){

    <li>@dog.Name (@dog.Age)</li>

}
</ul>

MyFirstMVCApplication/Views/Home/Demo.cshtml
@{
    ViewData["Title"] = "Demo Page";
}
<h1>@ViewData["Title"]</h1>

<p>Use this page to detail your site's privacy policy.</p>

MyFirstMVCApplication/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

MyFirstMVCApplication/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Dog Directory</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/MyFirstMVCApplication.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Dog Directory</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">                        
                         <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="HelloWorld" asp-action="Index">Dog List</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="HelloWorld" asp-action="Create">Add A Dog</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - MyFirstMVCApplication - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>